#!/bin/bash
echo "Remember to disable docker remove in host 4,5 and manually delete running containers."
REMOTE_USER="ubuntu"
REMOTE_IP1="192.168.120.151"
REMOTE_IP2="192.168.120.91"
REMOTE_IP3="192.168.120.79"
# REMOTE_IP4="192.168.120.134"
# REMOTE_IP5="192.168.120.234"

ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && docker rm -v -f $(docker ps -qa)"
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && docker container prune -f"
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && mv workspace/mnist/data-and-scratch{1,2,3} ."
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && mv workspace/mnist/data-and-edge{1,2,3} ."
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && rm -rf logs/ workspace host{1,2,3,4,5}"
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && docker rm -f sn{1,2,3} swop{1,2,3} swci1"
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && docker rm -f $(docker ps -a | grep 'user-env\|/sl:2' | awk '{print $1}')"
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && docker network rm host-{1,2,3}-net"
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && docker rm helper"
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && docker volume rm sl-cli-lib"
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && docker image rm tensorflow/tensorflow:2.7.1 user-env-tf2.7.0-swop:latest hello-world:latest"
ssh ${REMOTE_USER}@${REMOTE_IP1} "cd /opt/hpe/swarm-learning && docker volume rm $(docker volume ls -q | grep swop)"
ssh ${REMOTE_USER}@${REMOTE_IP1} "pwd && rm -rf SwarmLearningKLTN"
ssh ${REMOTE_USER}@${REMOTE_IP1} "docker ps -a"

ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && docker rm -v -f $(docker ps -qa)"
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && docker container prune -f"
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && mv workspace/mnist/data-and-scratch{1,2,3} ."
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && mv workspace/mnist/data-and-edge{1,2,3} ."
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && rm -rf logs/ workspace host{1,2,3,4,5}"
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && docker rm -f sn{1,2,3} swop{1,2,3} swci1"
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && docker rm -f $(docker ps -a | grep 'user-env\|/sl:2' | awk '{print $1}')"
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && docker network rm host-{1,2,3}-net"
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && docker rm helper"
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && docker volume rm sl-cli-lib"
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && docker image rm tensorflow/tensorflow:2.7.1 user-env-tf2.7.0-swop:latest hello-world:latest"
ssh ${REMOTE_USER}@${REMOTE_IP2} "cd /opt/hpe/swarm-learning && docker volume rm $(docker volume ls -q | grep swop)"
ssh ${REMOTE_USER}@${REMOTE_IP2} "rm -rf SwarmLearningKLTN"
ssh ${REMOTE_USER}@${REMOTE_IP2} "docker ps -a"